services:
  jupyter:
    build: .
    volumes:
      - ./project:/home/jovyan/template:ro
    ports:
      - "8888:8888"
    command: >
      bash -c "
      cp -rn /home/jovyan/template/* /home/jovyan/work/ &&
      start-notebook.sh --NotebookApp.token='' --LabApp.collaborative=True
      "
